[package]
name = "gitoxide-bug-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
git-repository = { version = "0.25.0", features = ["blocking-network-client", "blocking-http-transport"] }
tempdir = { version = "0.3.7" }
